- params:
    git:
      repoName: app-simple-maven
      branches:
        - develop
    scan:
      projects:
        - workingDirs:
            - .
      emailReceivers:
        - slash_mumu@163.com



